apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: llm-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: airflow
      containers:
      - name: scheduler
        image: airflow:latest
        imagePullPolicy: IfNotPresent
        command: ["airflow", "scheduler"]
        envFrom:
        - secretRef:
            name: airflow-secrets
        - configMapRef:
            name: airflow-config
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: logs
          mountPath: /opt/airflow/logs
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: dags
        configMap:
          name: airflow-dags
      - name: logs
        emptyDir: {}